* New representation of global variable to permit aliases (not   finished yet) * Some modification in configure scripts for usage without gc   installed

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -6705,7 +6705,8 @@ if test "$HAVE_GC" = "no"
 then
   echo "No Boehm-Demers-Weiser GC library. Using the one provided with the package"
   (cd gc; CC="$CC" CFLAGS="$CFLAGS" sh ./configure --prefix=$prefix \
-          --enable-threads=$THREADS) || { echo "Cannot configure the GC"; exit; }
+          --includedir=$prefix/include/stklos --enable-threads=$THREADS) \
+     || { echo "Cannot configure the GC"; exit; }
 
   GC=gc
   GCLIB="../gc/.libs/libgc.a"
