Added the configure option --with-control-fixnums
This option is on by default. Disabling it permit to have faster (but
less secure) fixnum functions

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -649,6 +649,7 @@ ac_func_c_list=
 ac_subst_vars='am__EXEEXT_FALSE
 am__EXEEXT_TRUE
 LTLIBOBJS
+CONTROL_FX_PARAMETERS
 DEFAULT_CS
 CONF_SUMMARY
 THREADS
@@ -696,9 +697,6 @@ POW_LIB
 LIBOBJS
 ALLOCA
 PKGCONFIG
-LEXLIB
-LEX_OUTPUT_ROOT
-LEX
 RANLIB
 LN_S
 CPP
@@ -805,6 +803,7 @@ with_provided_bignum
 with_gmp_light
 with_provided_regexp
 with_provided_ffi
+with_control_fixnums
 '
       ac_precious_vars='build_alias
 host_alias
@@ -1457,9 +1456,10 @@ Optional Packages:
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
   --with-provided-gc      use the provided Boehm GC library
   --with-provided-bignum  use the provided Bignum (GMPlite) library
-  --with-gmp-light      a synonym for --with-provided-bignum
-  --with-provided-regexp use the provided Regexp (PCRE) library
-  --with-provided-ffi    use the provided FFI library
+  --with-gmp-light        a synonym for --with-provided-bignum
+  --with-provided-regexp  use the provided Regexp (PCRE) library
+  --with-provided-ffi     use the provided FFI library
+  --with-control-fixnums  verify that fx functions are fixnums
 
 Some influential environment variables:
   CC          C compiler command
@@ -1629,53 +1629,6 @@ fi
 
 } # ac_fn_c_try_cpp
 
-# ac_fn_c_try_link LINENO
-# -----------------------
-# Try to link conftest.$ac_ext, and return whether this succeeded.
-ac_fn_c_try_link ()
-{
-  as_lineno=${as_lineno-"$1"} as_lineno_stack=as_lineno_stack=$as_lineno_stack
-  rm -f conftest.$ac_objext conftest.beam conftest$ac_exeext
-  if { { ac_try="$ac_link"
-case "(($ac_try" in
-  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
-  *) ac_try_echo=$ac_try;;
-esac
-eval ac_try_echo="\"\$as_me:${as_lineno-$LINENO}: $ac_try_echo\""
-printf "%s\n" "$ac_try_echo"; } >&5
-  (eval "$ac_link") 2>conftest.err
-  ac_status=$?
-  if test -s conftest.err; then
-    grep -v '^ *+' conftest.err >conftest.er1
-    cat conftest.er1 >&5
-    mv -f conftest.er1 conftest.err
-  fi
-  printf "%s\n" "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
-  test $ac_status = 0; } && {
-	 test -z "$ac_c_werror_flag" ||
-	 test ! -s conftest.err
-       } && test -s conftest$ac_exeext && {
-	 test "$cross_compiling" = yes ||
-	 test -x conftest$ac_exeext
-       }
-then :
-  ac_retval=0
-else $as_nop
-  printf "%s\n" "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-	ac_retval=1
-fi
-  # Delete the IPA/IPO (Inter Procedural Analysis/Optimization) information
-  # created by the PGI compiler (conftest_ipa8_conftest.oo), as it would
-  # interfere with the next link command; also delete a directory that is
-  # left behind by Apple's compiler.  We do this before executing the actions.
-  rm -rf conftest.dSYM conftest_ipa8_conftest.oo
-  eval $as_lineno_stack; ${as_lineno_stack:+:} unset as_lineno
-  as_fn_set_status $ac_retval
-
-} # ac_fn_c_try_link
-
 # ac_fn_c_check_header_compile LINENO HEADER VAR INCLUDES
 # -------------------------------------------------------
 # Tests whether HEADER exists and can be compiled using the include files in
@@ -1765,6 +1718,53 @@ printf "%s\n" "$ac_res" >&6; }
   eval $as_lineno_stack; ${as_lineno_stack:+:} unset as_lineno
 
 } # ac_fn_c_check_type
+
+# ac_fn_c_try_link LINENO
+# -----------------------
+# Try to link conftest.$ac_ext, and return whether this succeeded.
+ac_fn_c_try_link ()
+{
+  as_lineno=${as_lineno-"$1"} as_lineno_stack=as_lineno_stack=$as_lineno_stack
+  rm -f conftest.$ac_objext conftest.beam conftest$ac_exeext
+  if { { ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval ac_try_echo="\"\$as_me:${as_lineno-$LINENO}: $ac_try_echo\""
+printf "%s\n" "$ac_try_echo"; } >&5
+  (eval "$ac_link") 2>conftest.err
+  ac_status=$?
+  if test -s conftest.err; then
+    grep -v '^ *+' conftest.err >conftest.er1
+    cat conftest.er1 >&5
+    mv -f conftest.er1 conftest.err
+  fi
+  printf "%s\n" "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext && {
+	 test "$cross_compiling" = yes ||
+	 test -x conftest$ac_exeext
+       }
+then :
+  ac_retval=0
+else $as_nop
+  printf "%s\n" "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_retval=1
+fi
+  # Delete the IPA/IPO (Inter Procedural Analysis/Optimization) information
+  # created by the PGI compiler (conftest_ipa8_conftest.oo), as it would
+  # interfere with the next link command; also delete a directory that is
+  # left behind by Apple's compiler.  We do this before executing the actions.
+  rm -rf conftest.dSYM conftest_ipa8_conftest.oo
+  eval $as_lineno_stack; ${as_lineno_stack:+:} unset as_lineno
+  as_fn_set_status $ac_retval
+
+} # ac_fn_c_try_link
 
 # ac_fn_c_try_run LINENO
 # ----------------------
@@ -4934,286 +4934,7 @@ else
   RANLIB="$ac_cv_prog_RANLIB"
 fi
 
-
-for ac_prog in flex lex
-do
-  # Extract the first word of "$ac_prog", so it can be a program name with args.
-set dummy $ac_prog; ac_word=$2
-{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for $ac_word" >&5
-printf %s "checking for $ac_word... " >&6; }
-if test ${ac_cv_prog_LEX+y}
-then :
-  printf %s "(cached) " >&6
-else $as_nop
-  if test -n "$LEX"; then
-  ac_cv_prog_LEX="$LEX" # Let the user override the test.
-else
-as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
-for as_dir in $PATH
-do
-  IFS=$as_save_IFS
-  case $as_dir in #(((
-    '') as_dir=./ ;;
-    */) ;;
-    *) as_dir=$as_dir/ ;;
-  esac
-    for ac_exec_ext in '' $ac_executable_extensions; do
-  if as_fn_executable_p "$as_dir$ac_word$ac_exec_ext"; then
-    ac_cv_prog_LEX="$ac_prog"
-    printf "%s\n" "$as_me:${as_lineno-$LINENO}: found $as_dir$ac_word$ac_exec_ext" >&5
-    break 2
-  fi
-done
-  done
-IFS=$as_save_IFS
-
-fi
-fi
-LEX=$ac_cv_prog_LEX
-if test -n "$LEX"; then
-  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: $LEX" >&5
-printf "%s\n" "$LEX" >&6; }
-else
-  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: no" >&5
-printf "%s\n" "no" >&6; }
-fi
-
-
-  test -n "$LEX" && break
-done
-test -n "$LEX" || LEX=":"
-
-  if test "x$LEX" != "x:"; then
-    cat >conftest.l <<_ACEOF
-%{
-#ifdef __cplusplus
-extern "C"
-#endif
-int yywrap(void);
-%}
-%%
-a { ECHO; }
-b { REJECT; }
-c { yymore (); }
-d { yyless (1); }
-e { /* IRIX 6.5 flex 2.5.4 underquotes its yyless argument.  */
-#ifdef __cplusplus
-    yyless ((yyinput () != 0));
-#else
-    yyless ((input () != 0));
-#endif
-  }
-f { unput (yytext[0]); }
-. { BEGIN INITIAL; }
-%%
-#ifdef YYTEXT_POINTER
-extern char *yytext;
-#endif
-int
-yywrap (void)
-{
-  return 1;
-}
-int
-main (void)
-{
-  return ! yylex ();
-}
-_ACEOF
-{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for lex output file root" >&5
-printf %s "checking for lex output file root... " >&6; }
-if test ${ac_cv_prog_lex_root+y}
-then :
-  printf %s "(cached) " >&6
-else $as_nop
-
-ac_cv_prog_lex_root=unknown
-{ { ac_try="$LEX conftest.l"
-case "(($ac_try" in
-  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
-  *) ac_try_echo=$ac_try;;
-esac
-eval ac_try_echo="\"\$as_me:${as_lineno-$LINENO}: $ac_try_echo\""
-printf "%s\n" "$ac_try_echo"; } >&5
-  (eval "$LEX conftest.l") 2>&5
-  ac_status=$?
-  printf "%s\n" "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
-  test $ac_status = 0; } &&
-if test -f lex.yy.c; then
-  ac_cv_prog_lex_root=lex.yy
-elif test -f lexyy.c; then
-  ac_cv_prog_lex_root=lexyy
-fi
-fi
-{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: $ac_cv_prog_lex_root" >&5
-printf "%s\n" "$ac_cv_prog_lex_root" >&6; }
-if test "$ac_cv_prog_lex_root" = unknown
-then :
-  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: WARNING: cannot find output from $LEX; giving up on $LEX" >&5
-printf "%s\n" "$as_me: WARNING: cannot find output from $LEX; giving up on $LEX" >&2;}
-   LEX=: LEXLIB=
-fi
-LEX_OUTPUT_ROOT=$ac_cv_prog_lex_root
-
-if test ${LEXLIB+y}
-then :
-
-else $as_nop
-
-  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for lex library" >&5
-printf %s "checking for lex library... " >&6; }
-if test ${ac_cv_lib_lex+y}
-then :
-  printf %s "(cached) " >&6
-else $as_nop
-
-    ac_save_LIBS="$LIBS"
-    ac_found=false
-    for ac_cv_lib_lex in 'none needed' -lfl -ll 'not found'; do
-      case $ac_cv_lib_lex in #(
-  'none needed') :
-     ;; #(
-  'not found') :
-    break ;; #(
-  *) :
-    LIBS="$ac_cv_lib_lex $ac_save_LIBS" ;; #(
-  *) :
-     ;;
-esac
-
-      cat confdefs.h - <<_ACEOF >conftest.$ac_ext
-/* end confdefs.h.  */
-`cat $LEX_OUTPUT_ROOT.c`
-_ACEOF
-if ac_fn_c_try_link "$LINENO"
-then :
-  ac_found=:
-fi
-rm -f core conftest.err conftest.$ac_objext conftest.beam \
-    conftest$ac_exeext conftest.$ac_ext
-      if $ac_found; then
-        break
-      fi
-    done
-    LIBS="$ac_save_LIBS"
-
-fi
-{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: $ac_cv_lib_lex" >&5
-printf "%s\n" "$ac_cv_lib_lex" >&6; }
-  if test "$ac_cv_lib_lex" = 'not found'
-then :
-  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: WARNING: required lex library not found; giving up on $LEX" >&5
-printf "%s\n" "$as_me: WARNING: required lex library not found; giving up on $LEX" >&2;}
-	 LEX=: LEXLIB=
-elif test "$ac_cv_lib_lex" = 'none needed'
-then :
-  LEXLIB=''
-else $as_nop
-  LEXLIB=$ac_cv_lib_lex
-fi
-  ac_save_LIBS="$LIBS"
-      LIBS=
-      { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for library containing yywrap" >&5
-printf %s "checking for library containing yywrap... " >&6; }
-if test ${ac_cv_search_yywrap+y}
-then :
-  printf %s "(cached) " >&6
-else $as_nop
-  ac_func_search_save_LIBS=$LIBS
-cat confdefs.h - <<_ACEOF >conftest.$ac_ext
-/* end confdefs.h.  */
-
-/* Override any GCC internal prototype to avoid an error.
-   Use char because int might match the return type of a GCC
-   builtin and then its argument prototype would still apply.  */
-char yywrap ();
-int
-main (void)
-{
-return yywrap ();
-  ;
-  return 0;
-}
-_ACEOF
-for ac_lib in '' fl l
-do
-  if test -z "$ac_lib"; then
-    ac_res="none required"
-  else
-    ac_res=-l$ac_lib
-    LIBS="-l$ac_lib  $ac_func_search_save_LIBS"
-  fi
-  if ac_fn_c_try_link "$LINENO"
-then :
-  ac_cv_search_yywrap=$ac_res
-fi
-rm -f core conftest.err conftest.$ac_objext conftest.beam \
-    conftest$ac_exeext
-  if test ${ac_cv_search_yywrap+y}
-then :
-  break
-fi
-done
-if test ${ac_cv_search_yywrap+y}
-then :
-
-else $as_nop
-  ac_cv_search_yywrap=no
-fi
-rm conftest.$ac_ext
-LIBS=$ac_func_search_save_LIBS
-fi
-{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: $ac_cv_search_yywrap" >&5
-printf "%s\n" "$ac_cv_search_yywrap" >&6; }
-ac_res=$ac_cv_search_yywrap
-if test "$ac_res" != no
-then :
-  test "$ac_res" = "none required" || LIBS="$ac_res $LIBS"
-  LEXLIB="$LIBS"
-fi
-
-      LIBS="$ac_save_LIBS"
-fi
-
-
-if test "$LEX" != :
-then :
-
-{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking whether yytext is a pointer" >&5
-printf %s "checking whether yytext is a pointer... " >&6; }
-if test ${ac_cv_prog_lex_yytext_pointer+y}
-then :
-  printf %s "(cached) " >&6
-else $as_nop
-  # POSIX says lex can declare yytext either as a pointer or an array; the
-# default is implementation-dependent.  Figure out which it is, since
-# not all implementations provide the %pointer and %array declarations.
-ac_cv_prog_lex_yytext_pointer=no
-cat confdefs.h - <<_ACEOF >conftest.$ac_ext
-/* end confdefs.h.  */
-
-  #define YYTEXT_POINTER 1
-`cat $LEX_OUTPUT_ROOT.c`
-_ACEOF
-if ac_fn_c_try_compile "$LINENO"
-then :
-  ac_cv_prog_lex_yytext_pointer=yes
-fi
-rm -f core conftest.err conftest.$ac_objext conftest.beam conftest.$ac_ext
-
-fi
-{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: $ac_cv_prog_lex_yytext_pointer" >&5
-printf "%s\n" "$ac_cv_prog_lex_yytext_pointer" >&6; }
-if test $ac_cv_prog_lex_yytext_pointer = yes; then
-
-printf "%s\n" "#define YYTEXT_POINTER 1" >>confdefs.h
-
-fi
-
-fi
-rm -f conftest.l $LEX_OUTPUT_ROOT.c
-
-fi
+extraAC_PROG_LEX
 
 # Extract the first word of "pkg-config", so it can be a program name with args.
 set dummy pkg-config; ac_word=$2
@@ -5260,6 +4981,7 @@ fi
 
 
 ### Checks for header files.
+
 ac_header= ac_cache=
 for ac_item in $ac_header_c_list
 do
@@ -7438,6 +7160,27 @@ fi
 printf "%s\n" "#define HAVE_FFI 1" >>confdefs.h
 
 
+
+# ----------------------------------------------------------------------
+# Control fixnum parameters
+# ----------------------------------------------------------------------
+
+# Check whether --with-control-fixnums was given.
+if test ${with_control_fixnums+y}
+then :
+  withval=$with_control_fixnums; CONTROL_FX="$withval"
+else $as_nop
+  CONTROL_FX="yes"
+fi
+
+
+if test "$CONTROL_FX" = "yes"
+then
+    CONTROL_FX_PARAMETERS=1
+else
+    CONTROL_FX_PARAMETERS=0
+fi
+
 ###
 ### See in what direction the stack grows (code stolen from Sawfish)
 ###
@@ -7523,6 +7266,7 @@ fi
 
 
 # FFI
+
 
 
 
@@ -9034,6 +8778,7 @@ echo "    Compilation flags: " $CFLAGS
 echo "               Loader: " $LD
 echo "       Thread support: " $THREADS
 echo "     Case sensitivity: " $CASE_SENSITIVE '(by default)'
+echo "Control fx parameters: " $CONTROL_FX
 echo "System libraries used: " $SYST_LIBS
 echo "   Compiled libraries: " $COMP_LIBS
 echo " "
