Added a regression test for regexp + Bug correction for REGEXP-QUOTE

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -600,7 +600,6 @@ DEF_PCRE
 PCREINC
 PCRELIB
 PCRE
-PCRETARGET
 LDAP_LIB
 HAVE_GNOME
 STACK_DIRECTION
@@ -1373,7 +1372,7 @@ Optional Packages:
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
   --with-gmp-light		use our GMP version even the system provides one
   --with-provided-gc		use our GC version even the system provides one
-  --with-provided-regexp	use our PCRE regexp version
+  --with-provided-regexp	use the provided Regexp (PCRE) library
   --with-provided-ffi	use the provided FFI library
 
 Some influential environment variables:
@@ -6552,9 +6551,98 @@ case `uname -s` in
 esac
 
 
+#1.0###
+#1.0### check for PCRE
+#1.0###
+#1.0AC_CHECK_LIB(pcre, pcre_fullinfo, HAVE_PCRE="yes", HAVE_PCRE="no", $LIBS)
+#1.0
+#1.0# Test if the user want to force with our PCRE lib
+#1.0withval=""
+#1.0AC_ARG_WITH(provided-regexp,
+#1.0       [  --with-provided-regexp	use our PCRE regexp version])
+#1.0
+#1.0case $withval in
+#1.0  "yes") HAVE_PCRE="no";;
+#1.0  "no")  HAVE_PCRE="yes";;
+#1.0esac
+
 ###
-### check for PCRE
+### configure libraries
 ###
+
+if test "$HAVE_GMP" = "no"
+then
+  echo "No GMP library. Using the one provided with the package"
+  cmd="CC=\"$CC\" CFLAGS=\"$CFLAGS\" ./configure --prefix=$prefix"
+  echo "Configuring GMP"
+  echo $cmd
+  (cd gmp; eval $cmd)
+  GMP=gmp
+  GMPLIB="../gmp/libgmp.a"
+  GMPINC="-I../gmp"
+else
+  echo "Using the system GMP library"
+  GMP=""
+  GMPLIB="-lgmp"
+  GMPINC=""
+fi
+
+if test "$HAVE_GC" = "no"
+then
+  echo "No Boehm-Demers-Weiser GC library. Using the one provided with the package"
+  (cd gc; CC="$CC" CFLAGS="$CFLAGS" sh ./configure --prefix=$prefix \
+          --includedir=$prefix/include/stklos \
+          --enable-threads=$THREADS) || { echo "Cannot configure the GC"; exit; }
+
+  GC=gc
+  GCLIB="../gc/.libs/libgc.a"
+  GCINC="-I../gc/include"
+  # Eventually add a distclean target to the GC Makefile
+else
+  echo "Using the system Boehm-Demers-Weiser library"
+  GC=""
+  GCLIB="-lgc"
+  GCINC=""
+
+$as_echo "#define HAVE_GC /**/" >>confdefs.h
+
+fi
+
+#1.0 if test "$HAVE_PCRE" = "no"
+#1.0 then
+#1.0    echo "No PCRE library. Using the one provided with the package"
+#1.0    PCRE_FLAGS="-Dregexec=PCRE_regexec -Dregcomp=PCRE_regcomp \
+#1.0    -Dregerror=PCRE_regerror -Dregfree=PCRE_regfree"
+#1.0
+#1.0    (cd pcre; CC=$CC CFLAGS="$CFLAGS $PCRE_FLAGS" sh ./configure \
+#1.0     --prefix=$prefix --disable-shared --disable-cpp)
+#1.0     PCRE=pcre
+#1.0     PCRELIB="../pcre/.libs/libpcreposix.a ../pcre/.libs/libpcre.a"
+#1.0     PCREINC="-I../pcre"
+#1.0     DEF_PCRE=""
+#1.0 else
+#1.0       echo "Using the system PCRE library"
+#1.0      PCRE=""
+#1.0      PCRELIB="-lpcre -lpcreposix"
+#1.0      PCREINC=""
+#1.0      DEF_PCRE="#define HAVE_PCRE 1"
+#1.0 fi
+
+
+#PCRELIBS="../pcre/.libs/libpcreposix.a ../pcre/.libs/libpcre.a"
+#
+# case `uname -s` in
+#   CYGWIN*) PCRETARGET="libpcre.la";;
+#   *)       PCRETARGET="libpcre.la libpcreposix.la";;
+# esac
+
+# ----------------------------------------------------------------------
+# PCRE support
+# ----------------------------------------------------------------------
+echo "*****"
+echo "***** Regexp support"
+echo "*****"
+
 { $as_echo "$as_me:${as_lineno-$LINENO}: checking for pcre_fullinfo in -lpcre" >&5
 $as_echo_n "checking for pcre_fullinfo in -lpcre... " >&6; }
 if test "${ac_cv_lib_pcre_pcre_fullinfo+set}" = set; then :
@@ -6599,92 +6687,44 @@ fi
 
 
 # Test if the user want to force with our PCRE lib
-withval=""
 
 # Check whether --with-provided-regexp was given.
 if test "${with_provided_regexp+set}" = set; then :
-  withval=$with_provided_regexp;
+  withval=$with_provided_regexp; HAVE_PCRE="no"
+else
+  HAVE_PCRE="yes"
 fi
 
 
-case $withval in
-  "yes") HAVE_PCRE="no";;
-  "no")  HAVE_PCRE="yes";;
+case $HAVE_PCRE in
+  no)
+       echo "... Configuring libpcre"
+       PCRE_FLAGS="-Dregexec=PCRE_regexec -Dregcomp=PCRE_regcomp \
+       	           -Dregerror=PCRE_regerror -Dregfree=PCRE_regfree"
+       (cd pcre; CC=${CC} CFLAGS="${CFLAGS} $PCRE_FLAGS" ./configure \
+           --prefix=$prefix --disable-shared --disable-cpp)
+       PCRE=pcre
+       PCRELIB="../pcre/.libs/libpcreposix.a ../pcre/.libs/libpcre.a"
+       PCREINC="-I../pcre"
+       DEF_PCRE=""
+       pcrelib="use provided library";;
+  yes)
+       echo "... Using system libpcre library"
+       PCRE=""
+       PCRELIB="-lpcre -lpcreposix"
+       PCREINC=""
+       DEF_PCRE="#define HAVE_PCRE 1"
+       pcrelib="use the system library";;
 esac
 
-###
-### configure libraries
-###
 
-if test "$HAVE_GMP" = "no"
-then
-  echo "No GMP library. Using the one provided with the package"
-  cmd="CC=\"$CC\" CFLAGS=\"$CFLAGS\" ./configure --prefix=$prefix"
-  echo "Configuring GMP"
-  echo $cmd
-  (cd gmp; eval $cmd)
-  GMP=gmp
-  GMPLIB="../gmp/libgmp.a"
-  GMPINC="-I../gmp"
-else
-  echo "Using the system GMP library"
-  GMP=""
-  GMPLIB="-lgmp"
-  GMPINC=""
-fi
-
-if test "$HAVE_GC" = "no"
-then
-  echo "No Boehm-Demers-Weiser GC library. Using the one provided with the package"
-  (cd gc; CC="$CC" CFLAGS="$CFLAGS" sh ./configure --prefix=$prefix \
-          --includedir=$prefix/include/stklos \
-          --enable-threads=$THREADS) || { echo "Cannot configure the GC"; exit; }
-
-  GC=gc
-  GCLIB="../gc/.libs/libgc.a"
-  GCINC="-I../gc/include"
-  # Eventually add a distclean target to the GC Makefile
-else
-  echo "Using the system Boehm-Demers-Weiser library"
-  GC=""
-  GCLIB="-lgc"
-  GCINC=""
-
-$as_echo "#define HAVE_GC /**/" >>confdefs.h
-
-fi
-
-if test "$HAVE_PCRE" = "no"
-then
-   echo "No PCRE library. Using the one provided with the package"
-   PCRE_FLAGS="-Dregexec=PCRE_regexec -Dregcomp=PCRE_regcomp \
-   -Dregerror=PCRE_regerror -Dregfree=PCRE_regfree"
-
-   (cd pcre; CC=$CC CFLAGS="$CFLAGS $PCRE_FLAGS" sh ./configure \
-    --prefix=$prefix --disable-shared --disable-cpp)
-    PCRE=pcre
-    PCRELIB="../pcre/.libs/libpcreposix.a ../pcre/.libs/libpcre.a"
-    PCREINC="-I../pcre"
-    DEF_PCRE=""
-else
-      echo "Using the system PCRE library"
-     PCRE=""
-     PCRELIB="-lpcre -lpcreposix"
-     PCREINC=""
-     DEF_PCRE="#define HAVE_PCRE 1"
-fi
-
-
-#PCRELIBS="../pcre/.libs/libpcreposix.a ../pcre/.libs/libpcre.a"
-#
-# case `uname -s` in
-#   CYGWIN*) PCRETARGET="libpcre.la";;
-#   *)       PCRETARGET="libpcre.la libpcreposix.la";;
-# esac
-
-#
+# ----------------------------------------------------------------------
 # FFI support
-#
+# ----------------------------------------------------------------------
+echo "*****"
+echo "***** FFI support"
+echo "*****"
+
 { $as_echo "$as_me:${as_lineno-$LINENO}: checking for ffi_prep_cif in -lffi" >&5
 $as_echo_n "checking for ffi_prep_cif in -lffi... " >&6; }
 if test "${ac_cv_lib_ffi_ffi_prep_cif+set}" = set; then :
@@ -6729,7 +6769,6 @@ fi
 
 
 # Test if the user want to force with our FFI lib
-withval=
 
 # Check whether --with-provided-ffi was given.
 if test "${with_provided_ffi+set}" = set; then :
@@ -6741,9 +6780,7 @@ fi
 
 case $HAVE_FFI in
   no)
-       echo "*****"
-       echo "***** Configuring libffi"
-       echo "*****"
+       echo "... Configuring libffi"
        (cd ffi; CC=${CC} CFLAGS=${CFLAGS} ./configure \
            --disable-structs --disable-raw-api --disable-shared \
 	   --prefix=$prefix)
@@ -6752,9 +6789,7 @@ case $HAVE_FFI in
        FFI="ffi"
        ffilib="use provided library";;
   yes)
-       echo "*****"
-       echo "***** Using system libffi library"
-       echo "*****"
+       echo "... Using system libffi library"
        CFLAGS="$CFLAGS `pkg-config libffi --cflags`"
        LIBS="$LIBS `pkg-config libffi --libs`"
        FFI=""
@@ -6797,34 +6832,6 @@ OS_NAME=$OS
 ### Place version number in VERSION file
 ### echo "VERSION=${VERSION}">VERSION
 
-#1.0 ### GTK+/GNOME support
-#1.0 HAVE_GNOME="undef"
-#1.0
-#1.0 if test "$USE_GTK" = "no" ;then
-#1.0    USE_GNOME="no"
-#1.0 fi
-#1.0
-#1.0
-#1.0 if test "$USE_GTK" = "yes"
-#1.0 then
-#1.0   GTKLOS=gtklos
-#1.0   EXAMPLES="examples examples/images"
-#1.0
-#1.0   if test "$USE_GNOME" = "yes"
-#1.0   then
-#1.0     HAVE_GNOME="define"
-#1.0     GTK_CONFIG_LIBS=`$GNOME_CONFIG --libs  gnomecanvaspixbuf`
-#1.0     GTK_CONFIG_CFLAGS=`$GNOME_CONFIG --cflags gnomeui gnomecanvaspixbuf`
-#1.0   else
-#1.0     GTK_CONFIG_LIBS=`$GTK_CONFIG --libs`
-#1.0     GTK_CONFIG_CFLAGS=`$GTK_CONFIG --cflags`
-#1.0   fi
-#1.0 else
-#1.0   GTKLOS=
-#1.0   EXAMPLES=
-#1.0   GTK_CONFIG_LIBS=
-#1.0   GTK_CONFIG_CFLAGS=
-#1.0 fi
 
 ###
 ### display some informations for the user
@@ -6844,18 +6851,13 @@ else
   gclib="use the system library"
 fi
 
-if test "$HAVE_PCRE" = "no"
-then
-  pcrelib="compile provided library"
-else
-  pcrelib="use the system library"
-fi
-
-#1.0 # Compute SVN_URL
-#1.0 SVN_URL=$SVN_REPOSITORY
-#1.0 if test "$SVN_REPOSITORY" = "" ;then
-#1.0    SVN_URL="NOT_AVAILABLE"
+#1.0 if test "$HAVE_PCRE" = "no"
+#1.0 then
+#1.0   pcrelib="compile provided library"
+#1.0 else
+#1.0   pcrelib="use the system library"
 #1.0 fi
+
 
 # LURC adjustment
 LURCDIR=""
@@ -6911,19 +6913,13 @@ fi
 
 
 
-#1.0 AC_SUBST(GTKLOS)
-#1.0 AC_SUBST(GTK_CONFIG_LIBS)
-#1.0 AC_SUBST(GTK_CONFIG_CFLAGS)
-#1.0 AC_SUBST(EXAMPLES)
 
-#1.0 AC_SUBST(HAVE_LDAP)
+
+#1.0 AC_SUBST(PCRETARGET)
 
 
 
 
-
-
-#1.0 AC_SUBST(SVN_URL)
 
 
 
@@ -8410,9 +8406,6 @@ echo " Compilation flags: " $CFLAGS
 echo "    Bignum library: " $biglib
 echo "    Regexp library: " $pcrelib
 echo "        GC library: " $gclib
-#1.0 echo "      LDAP support: " $USE_LDAP
-#1.0 echo "      GTK+ support: " $USE_GTK
-#1.0 echo "     GNOME support: " $USE_GNOME
 echo "       FFI library: " $ffilib
 echo "    Thread support: " $THREADS
 echo " "
