Get rid of boot.img in the git
Boot.img and boot.c are necessary to bootstap STklos. However,
boot.img is a huge file with very long lines. Since, it is which is
often rebuild, it is a real problem with git (particularly when
merging branches with important changes). However, since both files
contain the same information, the first compilation of the build of a
new image uses the image embedded in the executable (instead of the
external boot.img).

diff --git a/lib/Makefile.in b/lib/Makefile.in
--- a/lib/Makefile.in
+++ b/lib/Makefile.in
@@ -36,7 +36,7 @@
 #
 #           Author: Erick Gallesio [eg@unice.fr]
 #    Creation date: 11-Apr-2000 10:30 (eg)
-# Last file update:  4-Mar-2023 11:53 (eg)
+# Last file update:  7-Mar-2023 20:24 (eg)
 
 VPATH = @srcdir@
 am__is_gnu_make = { \
@@ -466,7 +466,7 @@ BASEDIR = ..
 schemedir = $(prefix)/share/@PACKAGE@/@VERSION@
 schemelibdir = $(prefix)/lib/@PACKAGE@/@VERSION@
 scheme_DATA = $(scheme_extra) $(scheme_OBJS)
-schemelib_DATA = $(scheme_SOLIBS) 
+schemelib_DATA = $(scheme_SOLIBS)
 scheme_sources = $(scheme_BOOT) $(scheme_extra) $(SRC_STK) $(SRC_C)
 #======================================================================
 SUFFIXES = .stk .ostk .scm  -incl.c  .$(SH_SUFFIX) .c
@@ -855,7 +855,7 @@ generate-git-info:
 ../src/boot.img: $(scheme_BOOT)
 	@echo "*** Boot 0"; \
 	(export STKLOS_BUILDING=1; \
-	$(STKLOS_BINARY) $(STKLOS_FLAGS) -b ../src/boot.img -f bb.stk boot.img0 instr0)
+	$(STKLOS_BINARY) $(STKLOS_FLAGS) -f bb.stk boot.img0 instr0)
 	@echo "*** Boot 1"; \
 	(export STKLOS_BUILDING=1; \
 	$(STKLOS_BINARY) $(STKLOS_FLAGS) -b ./boot.img0     -f bb.stk boot.img1 instr1)
@@ -865,22 +865,21 @@ generate-git-info:
 	@echo "*** Boot 3"; \
 	(export STKLOS_BUILDING=1; \
 	$(STKLOS_BINARY) $(STKLOS_FLAGS) -b ./boot.img2     -f bb.stk boot.img3 instr3)
-	@if cmp ./boot.img2 ./boot.img3 ;then 				\
-	   echo "*** New boot file created";  				\
-	   cp ../src/boot.img ../src/boot.keep;				\
-	   cp ./boot.img3 ../src/boot.img;    				\
-	   cp ./instr3    ../src/vm-instr.h;  				\
-	   echo "*** Create new boot.c";				\
-	   (export STKLOS_BUILDING=1;					\
-	    $(STKLOS_BINARY) $(STKLOS_FLAGS) -b ../src/boot.img  	\
-		-f make-C-boot.stk -- boot.img3 ../src/boot.c);		\
-	   echo "*** Recompile STklos";					\
-	   (cd ../src; $(MAKE) stklos);					\
-	   echo "*** Cleaning useless images";				\
-	   /bin/rm boot.img[0-3] instr[0-3];  				\
-	else 								\
-	   echo "*** Boot file creation failed"; 			\
-	   exit 1; 							\
+	@if cmp ./boot.img2 ./boot.img3 ;then                      \
+	   echo "*** New boot file created";                       \
+	   cp ./boot.img3 ../src/boot.img;                         \
+	   cp ./instr3    ../src/vm-instr.h;                       \
+	   echo "*** Create new boot.c";                           \
+	   (export STKLOS_BUILDING=1;                              \
+		$(STKLOS_BINARY) $(STKLOS_FLAGS) -b ../src/boot.img    \
+		-f make-C-boot.stk -- boot.img3 ../src/boot.c);        \
+	   echo "*** Recompile STklos";                            \
+	   (cd ../src; $(MAKE) stklos);                            \
+	   echo "*** Cleaning useless images";                     \
+	   /bin/rm boot.img[0-3] instr[0-3];                       \
+	else                                                       \
+	   echo "*** Boot file creation failed";                   \
+	   exit 1;                                                 \
 	fi;
 
 # Installation of *.stk files
@@ -890,7 +889,7 @@ install-sources:
 	done
 	cp $(SRC_STK) $(scheme_BOOT) $(DESTDIR)/$(schemedir)
 
-# Explicit some dependencies here 
+# Explicit some dependencies here
 $(SCHEME_OBJS): ../src/boot.img
 ffi.ostk: bigmatch.ostk
 bigmatch.ostk: Match.d/compiler.scm Match.d/descr.scm Match.d/mexpand.scm \
@@ -907,7 +906,7 @@ lib/stklos: lib
 lib/streams: lib
 lib/srfi: lib/scheme lib/stklos lib/streams
 
-readline-complete.@SH_SUFFIX@: readline-complete.c 
+readline-complete.@SH_SUFFIX@: readline-complete.c
 	@CC@ @CFLAGS@ @STKCFLAGS@ @SH_COMP_FLAGS@ -I../src @GCINC@ \
 	-c -o $*.o $*.c
 	@SH_LOADER@ @SH_LOAD_FLAGS@ -o $*.@SH_SUFFIX@ $*.o @DLLIBS@ @RDLINE@
